# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm ci
          rm -rf test/bats test/test_helper
          git rm -rf test/bats test/test_helper
          git submodule add https://github.com/bats-core/bats-core.git test/bats
          git submodule add https://github.com/bats-core/bats-support.git test/test_helper/bats-support
          git submodule add https://github.com/bats-core/bats-assert.git test/test_helper/bats-assert
          echo API_TELEGRAM_TOKEN="${{secrets.API_TELEGRAM_TOKEN}}" >> .env
      - run: npm test
        env:
          API_TELEGRAM_ID: ${{secrets.API_TELEGRAM_ID}}
          API_TELEGRAM_HASH: ${{secrets.API_TELEGRAM_HASH}}
          PHONE_TEST: ${{secrets.PHONE_TEST}}
          DEFAULT_INFO_FORMAT: ${{vars.DEFAULT_INFO_FORMAT}}
          AUTOSAVE: ${{vars.AUTOSAVE}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
